server:
  port: 9898

#debug: true

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 60s
#      routes:
#        - id: TEST-SERVICE
#          uri: http://example.org
#          predicates:
#            - Path=/**
#          filters:
#            - Logging
#            - name: Retry
#              args:
#                retries: 3
#                statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
#                methods: GET,POST

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://10.50.30.191:8761/eureka/,http://10.50.30.192:8761/eureka/,http://10.50.30.193:8761/eureka/,http://10.50.30.194:8761/eureka/,http://10.50.30.195:8761/eureka/
