spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/test
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.example.ddd.infrastructure.conf.hibernate.PhysicalNamingStrategyImpl
    properties: # @see org.hibernate.cfg.AvailableSettings
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 25
      hibernate.format_sql: true
#      hibernate.allow_update_outside_transaction: true
#      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#  transaction:
#    rollback-on-commit-failure: true