spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
      repositories:
        enabled: false

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: trace