spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/test
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties: # @see org.hibernate.cfg.AvailableSettings
      hibernate.format_sql: true
#      hibernate.allow_update_outside_transaction: true
#      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#  transaction:
#    rollback-on-commit-failure: true
#logging:
#  level:
#    org.hibernate: debug