spring:
  r2dbc:
    url: r2dbc:mysql://10.50.30.166/o_gateway
    username: oceanum
    password: lygr@0907
    pool:
      validation-query: SELECT 1


logging:
  level:
    org.springframework.r2dbc: debug